import {
  CONTEXTTEND_VERSION,
  type Config,
  type ExternalSourceRegistry,
} from "./domain.js";
import { sha256 } from "./hashing.js";

function lines(...items: string[]): string {
  return `${items.join("\n")}\n`;
}

export const GOVERNANCE_GUIDE = lines(
  "# ContextTend agent governance",
  "",
  "This file is managed by ContextTend. Project meaning lives in the sources",
  "registered in `.contexttend/registry.yaml`, not in this guide.",
  "",
  "## Authority",
  "",
  "- `canonical`: declared source of truth for its role.",
  "- `evidence`: observable implementation or verification facts.",
  "- `supporting`: useful context that does not override canonical knowledge.",
  "- `generated`: reproducible output; do not edit manually.",
  "- `historical`: retained context that is no longer current.",
  "- `external`: knowledge governed outside ContextTend.",
  "",
  "When sources disagree, report the conflict. Do not silently pick the newest",
  "file or infer product intent from implementation evidence.",
  "",
  "## Ownership",
  "",
  "- `human`: change meaning only when the user directly supplies or approves it.",
  "- `shared`: change after verified evidence of the underlying project change.",
  "- `agent`: maintain when evidence is sufficient and cite that evidence.",
  "- `system`: change only through the deterministic ContextTend CLI.",
  "- `generated`: regenerate through its owner; never hand-edit.",
  "- `external`: read-only to ContextTend; use the owning tool's workflow.",
  "",
  "## Promotion",
  "",
  "Move uncertain knowledge through observation -> candidate -> review -> durable",
  "knowledge. Put unresolved proposals in `.contexttend/candidates/` with claim,",
  "role, evidence, confidence, proposed owner, and recommended destination.",
  "",
  "## Evidence",
  "",
  "Every semantic finding names the claim, canonical source, conflicting or",
  "supporting evidence, confidence, and recommended action. `unknown` is valid;",
  "fabricated certainty is not.",
);

const ONBOARD_SKILL = lines(
  "---",
  "name: context-onboard",
  "description: Onboard a repository on the first substantive Codex task after ContextTend init. Use automatically when `.contexttend/state.json` has no `lastOnboarding`, or explicitly via $context-onboard, to audit and route existing AGENTS.md and overlapping project knowledge before normal work.",
  "---",
  "",
  "# Context onboarding",
  "",
  "Complete the semantic half of ContextTend initialization, then return to the",
  "user's original task. Deterministic `contexttend init` owns structure; this",
  "Skill owns evidence-backed understanding, consolidation, and routing.",
  "",
  "## Related Skills",
  "",
  "Read a related Skill's `SKILL.md` completely before using that phase. Its",
  "current contract wins; do not duplicate or weaken it here.",
  "",
  "- `$harness-audit full`: verify non-managed AGENTS content and existing Codex",
  "  Skills, plugins, configuration, or discovery assumptions. It reports only.",
  "- `$memory-audit`: report stale, contradictory, duplicate, unsupported,",
  "  misowned, and overloaded durable knowledge before consolidation.",
  "- `$context-bootstrap`: fill missing native sources from verified evidence",
  "  after existing sources and external owners have been identified.",
  "- `$context-sync`: maintain durable knowledge after onboarding and material",
  "  repository changes; it is not a substitute for first-run consolidation.",
  "",
  "## Workflow",
  "",
  "1. Preserve the user's original request. Locate the repository root; read",
  "   `.contexttend/state.json`, `.contexttend/registry.yaml`, and the governance",
  "   guide completely. If `lastOnboarding` is already set and onboarding was not",
  "   explicitly requested, resume the original task without rerunning this flow.",
  "2. Run `contexttend validate`. Stop semantic writes when deterministic",
  "   infrastructure is invalid and report the exact remediation.",
  "3. Read `AGENTS.md` completely. Separate the marker-bounded ContextTend block",
  "   from user-authored content and split the latter into coherent claims or",
  "   instruction blocks with source locations. Treat existing text as claims to",
  "   verify, not as proof that product or implementation facts are current.",
  "4. Inventory conventional documentation, registered sources, external",
  "   framework artifacts, code, tests, and configuration. Read likely canonical",
  "   sources first and expand only where a claim overlaps, conflicts, or lacks",
  "   evidence. Never create a second source of truth owned by an adapter.",
  "5. When non-managed AGENTS content or a non-ContextTend Codex harness exists,",
  "   use `$harness-audit full` as a read-only phase. When sources overlap or",
  "   freshness is doubtful, use `$memory-audit` as a read-only phase. Continue",
  "   only with findings supported by repository or authoritative evidence.",
  "6. Classify every AGENTS block and overlapping durable claim as `KEEP`,",
  "   `MOVE`, `CONDENSE`, `CANDIDATE`, `REMOVE`, or `EXTERNAL`. For each item",
  "   provide source, claim, evidence, confidence, registered destination, owner,",
  "   and proposed action. Unsupported or disputed claims become candidates; they",
  "   are never promoted merely because AGENTS.md states them.",
  "7. Present one `ONBOARDING PLAN` before mutation. Include files to change,",
  "   exact knowledge routing, conflicts and unknowns, content that would remain",
  "   in AGENTS.md, and content proposed for removal. Ask for confirmation before",
  "   shortening, replacing, or removing pre-existing user-authored content unless",
  "   the user's current request already explicitly authorizes that migration.",
  "8. Apply the approved plan. Use `$context-bootstrap` for missing native",
  "   knowledge. Write a verified destination before removing its source text;",
  "   preserve unresolved material as candidates; keep AGENTS.md as a concise",
  "   operational map; and never modify external or generated sources directly.",
  "9. Recheck the affected claims and run `contexttend validate` plus",
  "   `contexttend diff`. On success, run `contexttend record sync` and",
  "   `contexttend record onboarding`. Do not record completion when required",
  "   migration was declined, validation failed, or material claims were dropped.",
  "10. Report sources inspected, Skill phases used or skipped, files changed,",
  "    claims kept/moved/condensed/candidate/removed, unknowns, and validation.",
  "    Then resume the user's original task unless it is no longer applicable.",
  "",
  "A completed onboarding may retain explicit unknowns and candidates. Do not",
  "rerun it merely because code changed; use sync or the focused audits instead.",
  "Never edit ContextTend-managed assets or machine state directly.",
);

const BOOTSTRAP_SKILL = lines(
  "---",
  "name: context-bootstrap",
  "description: Bootstrap or repair missing or placeholder typed project knowledge after ContextTend init. Use when canonical knowledge is incomplete or the user invokes $context-bootstrap; do not replace an external spec framework.",
  "---",
  "",
  "# Context bootstrap",
  "",
  "Create useful durable knowledge from repository evidence without inventing",
  "product intent.",
  "",
  "## Workflow",
  "",
  "1. Locate the repository root and read `.contexttend/registry.yaml` completely.",
  "2. Read `.contexttend/guides/agent-governance.md` completely.",
  "3. Run `contexttend validate`. Stop semantic writes if deterministic",
  "   infrastructure is invalid; report the exact findings.",
  "4. Build a role coverage table from the registry. Treat external adapter",
  "   sources as read-only and use them instead of parallel ContextTend docs.",
  "5. Route progressively: read canonical goals/product first when needed, then",
  "   only architecture, requirements, decisions, plans, code, and tests relevant",
  "   to each missing claim. Do not read every spec or decision by default.",
  "6. Fill missing or placeholder knowledge in native sources only, including",
  "   scaffold `Unknown` sections. Preserve complete verified content. For `human`",
  "   ownership, use direct user statements or clearly cited existing product",
  "   documentation. If intent is unavailable, write",
  "   `Unknown - human confirmation required` and list the evidence inspected;",
  "   never turn code behavior into a product requirement.",
  "7. For `shared` sources, state the verified evidence behind every durable",
  "   claim. For `agent` sources, keep summaries concise and reproducible.",
  "8. Put disputed observations in `.contexttend/candidates/`; do not promote",
  "   them merely because they appear implemented.",
  "9. Run `contexttend validate` again and report sources read, files changed,",
  "   unknowns, candidates, and validation outcome.",
  "",
  "Never modify `.contexttend/state.json`, managed Skill files, generated files,",
  "or external framework artifacts directly.",
);

const SYNC_SKILL = lines(
  "---",
  "name: context-sync",
  "description: Perform a documentation impact check after material repository changes. Use when the user invokes $context-sync or asks whether durable project knowledge must change.",
  "---",
  "",
  "# Context sync",
  "",
  "Determine whether repository changes require durable knowledge updates.",
  "",
  "## Workflow",
  "",
  "1. Read `.contexttend/registry.yaml` and the governance guide completely.",
  "2. Run `contexttend validate` and `contexttend diff`.",
  "3. Inspect `git status --short`, the relevant git diff, changed tests, and",
  "   active external specs/plans. Never store raw transcripts.",
  "4. Answer each impact question with yes/no/unknown and evidence:",
  "   product behavior, architecture, business rule, public interface, security",
  "   assumption, reliability behavior, durable decision, accepted limitation,",
  "   and completed plan.",
  "5. Route only to registered roles affected by a yes/unknown answer.",
  "6. Apply ownership policy. Human-owned meaning needs direct user evidence;",
  "   shared knowledge needs a confirmed project change; agent-owned summaries",
  "   may be maintained from strong evidence; external/generated sources are not",
  "   edited through ContextTend.",
  "7. Write uncertain claims as candidates. If every answer is no, explicitly",
  "   report `No durable knowledge update required.`",
  "8. Run validation again. If successful, run `contexttend record sync`.",
  "",
  "Report the evidence, affected role, canonical destination, ownership decision,",
  "and exact changes. Do not update documentation simply because files changed.",
);

const MEMORY_AUDIT_SKILL = lines(
  "---",
  "name: memory-audit",
  "description: Audit durable project knowledge against repository evidence for staleness, contradiction, duplication, orphaning, unsupported claims, supersession, missing sources, ownership errors, and overload. Read-only except for the audit report.",
  "---",
  "",
  "# Memory audit",
  "",
  "Audit whether durable knowledge still matches the project.",
  "",
  "## Workflow",
  "",
  "1. Read the registry and governance guide. Run `contexttend validate` and",
  "   include its findings rather than rediscovering path/schema facts.",
  "2. Inventory registered sources by role, authority, owner, and adapter.",
  "3. Use progressive disclosure. For each claim under review, inspect its",
  "   canonical source and only the relevant code, tests, plans, decisions, or",
  "   external artifacts.",
  "4. Check every class: `STALE`, `CONTRADICTORY`, `DUPLICATE`, `ORPHAN`,",
  "   `UNSUPPORTED`, `SUPERSEDED`, `MISSING`, `MISOWNED`, and `OVERLOADED`.",
  "5. Explicitly test for stale architecture, contradictory product rules,",
  "   duplicate canonical sources, completed active plans, and missing registered",
  "   files. Absence of evidence is not automatically a contradiction.",
  "6. Assign P0 dangerous contradiction, P1 material stale knowledge, P2",
  "   structural problem, or P3 optional cleanup.",
  "7. Every finding must include: Finding, Claim, Canonical source, Conflicting",
  "   evidence, Confidence, and Recommended action. Omit unsupported guesses.",
  "8. Write `.contexttend/audits/YYYY-MM-DD-memory.md`. Do not change project",
  "   knowledge during the audit. Then run `contexttend record memory-audit`.",
  "",
  "The report begins with scope, registry version, commit or working-tree state,",
  "and deterministic validation summary. A clean audit is a valid result.",
);

const HARNESS_AUDIT_SKILL = lines(
  "---",
  "name: harness-audit",
  "description: Research current official Codex guidance and audit this repository's AGENTS.md, Skills, plugins, configuration, discovery paths, and adapter assumptions. Use $harness-audit for incremental checks or $harness-audit full for reconsideration.",
  "---",
  "",
  "# Harness audit",
  "",
  "Audit the coding-agent configuration, not the product.",
  "",
  "## Source policy",
  "",
  "Use fresh network research. Official OpenAI Codex/developer documentation and",
  "release notes are AUTHORITATIVE; explicit official recommendations are",
  "OFFICIAL_RECOMMENDATION; Cookbook examples are OFFICIAL_EXAMPLE; OpenAI",
  "engineering reports are EXPERIMENTAL_PRACTICE; community sources are",
  "COMMUNITY_PRACTICE and never override official sources.",
  "",
  "## Workflow",
  "",
  "1. Read `.contexttend/source-registry.yaml`, the registry, and governance guide.",
  "2. Without `full`, research changes since each relevant `lastChecked`; with",
  "   `full`, reconsider every recorded assumption.",
  "3. Fetch primary pages, not search snippets. Check AGENTS discovery and size",
  "   behavior, `.agents/skills` discovery, Skill metadata, plugin packaging,",
  "   Codex configuration, changelog/release notes, relevant Cookbook material,",
  "   OpenAI engineering publications, and external adapter contracts.",
  "4. Compare sources with the repository. Look for obsolete/conflicting rules,",
  "   changed discovery paths, overly large always-on context, deprecated config,",
  "   locally modified managed assets, and stale adapter assumptions.",
  "5. For every finding cite URL, source class, checked date, repository evidence,",
  "   confidence, and a reviewable proposal.",
  "6. Write `.contexttend/audits/YYYY-MM-DD-harness.md`. Do not migrate or rewrite",
  "   the project during the audit.",
  "7. After a successful report run",
  "   `contexttend record harness-audit --source openai-codex-docs`.",
  "",
  "Migration is always a separate explicit CLI operation. Never silently reshape",
  "AGENTS.md, Skills, framework directories, or semantic project knowledge.",
);

export const SYSTEM_ASSET_CONTENTS: Readonly<Record<string, string>> = {
  ".contexttend/guides/agent-governance.md": GOVERNANCE_GUIDE,
  ".contexttend/audits/.gitkeep": "",
  ".contexttend/candidates/.gitkeep": "",
  ".agents/skills/context-onboard/SKILL.md": ONBOARD_SKILL,
  ".agents/skills/context-bootstrap/SKILL.md": BOOTSTRAP_SKILL,
  ".agents/skills/context-sync/SKILL.md": SYNC_SKILL,
  ".agents/skills/memory-audit/SKILL.md": MEMORY_AUDIT_SKILL,
  ".agents/skills/harness-audit/SKILL.md": HARNESS_AUDIT_SKILL,
};

export const SYSTEM_ASSET_HASHES: Readonly<Record<string, string>> =
  Object.fromEntries(
    Object.entries(SYSTEM_ASSET_CONTENTS).map(([assetPath, content]) => [
      assetPath,
      sha256(content),
    ]),
  );

export const DEFAULT_CONFIG: Config = {
  version: 1,
  mode: "adaptive",
  agentIntegration: true,
  createMissingNativeSources: true,
};

export function defaultExternalSourceRegistry(
  checkedDate: string,
): ExternalSourceRegistry {
  return {
    version: 1,
    sources: {
      "openai-codex-docs": {
        authority: "authoritative",
        url: "https://learn.chatgpt.com/docs",
        lastChecked: checkedDate,
        relevantTopics: [
          "agents-md",
          "skills",
          "plugins",
          "configuration",
          "changelog",
        ],
      },
      "openai-codex-engineering": {
        authority: "experimental-practice",
        url: "https://openai.com/index/harness-engineering/",
        lastChecked: checkedDate,
        relevantTopics: [
          "progressive-disclosure",
          "repository-knowledge",
          "mechanical-validation",
        ],
      },
      "github-spec-kit": {
        authority: "authoritative",
        url: "https://github.com/github/spec-kit",
        lastChecked: checkedDate,
        relevantTopics: ["adapter", "specs", "skills-mode"],
      },
    },
  };
}

export const NATIVE_SOURCE_TEMPLATES: Readonly<Record<string, string>> = {
  "docs/GOALS.md": lines(
    "# Project goals",
    "",
    "Authority: human-owned canonical product intent.",
    "",
    "## Goals",
    "",
    "Unknown - human confirmation or `$context-bootstrap` with direct product",
    "evidence is required.",
    "",
    "## Non-goals",
    "",
    "Unknown - do not infer non-goals from missing implementation.",
    "",
    "## Success signals",
    "",
    "Unknown - define measurable outcomes with the project owner.",
  ),
  "docs/PRODUCT.md": lines(
    "# Product",
    "",
    "Authority: human-owned canonical product knowledge.",
    "",
    "## Problem and users",
    "",
    "Unknown - human confirmation or existing authoritative product evidence is",
    "required.",
    "",
    "## Product behavior",
    "",
    "Unknown - implementation behavior is evidence, not product intent.",
    "",
    "## Constraints",
    "",
    "No product constraints have been verified yet.",
  ),
  "docs/PLANS.md": lines(
    "# Plans",
    "",
    "Authority: shared canonical roadmap.",
    "",
    "## Active",
    "",
    "No active durable plan has been verified.",
    "",
    "## Completed",
    "",
    "No completed plan has been recorded.",
    "",
    "Move completed work out of Active only after verification evidence exists.",
  ),
  "docs/decisions/README.md": lines(
    "# Decisions",
    "",
    "Record durable architectural decisions here when no external decision system",
    "already owns them. Each decision should include context, decision,",
    "consequences, status, and evidence. Do not duplicate Spec Kit, OpenSpec,",
    "Agent OS, or GSD decisions.",
  ),
  "docs/context/README.md": lines(
    "# Implementation context",
    "",
    "Agent-maintained, evidence-backed summaries may live here. Keep them small,",
    "typed, and reproducible from code or tests. Do not store session transcripts",
    "or restate human product intent.",
  ),
};

export const CONTEXTTEND_META = lines(
  "<!-- contexttend:generated -->",
  "# ContextTend installation",
  "",
  `Managed by ContextTend ${CONTEXTTEND_VERSION}.`,
  "",
  "Use `.contexttend/registry.yaml` for the knowledge map and",
  "`.contexttend/state.json` for machine state. Do not edit managed assets by hand.",
);
