import {
  CONTEXTTEND_VERSION,
  type Config,
  type ExternalSourceRegistry,
} from "./domain.js";
import { sha256 } from "./hashing.js";

function lines(...items: string[]): string {
  return `${items.join("\n")}\n`;
}

export const GOVERNANCE_GUIDE = lines(
  "# ContextTend agent governance",
  "",
  "This file is managed by ContextTend. Project meaning lives in the sources",
  "registered in `.contexttend/registry.yaml`, not in this guide.",
  "",
  "## Authority",
  "",
  "- `canonical`: declared source of truth for its role.",
  "- `evidence`: observable implementation or verification facts.",
  "- `supporting`: useful context that does not override canonical knowledge.",
  "- `generated`: reproducible output; do not edit manually.",
  "- `historical`: retained context that is no longer current.",
  "- `external`: knowledge governed outside ContextTend.",
  "",
  "When sources disagree, report the conflict. Do not silently pick the newest",
  "file or infer product intent from implementation evidence.",
  "",
  "## Ownership",
  "",
  "- `human`: change meaning only when the user directly supplies or approves it.",
  "- `shared`: change after verified evidence of the underlying project change.",
  "- `agent`: maintain when evidence is sufficient and cite that evidence.",
  "- `system`: change only through the deterministic ContextTend CLI.",
  "- `generated`: regenerate through its owner; never hand-edit.",
  "- `external`: read-only to ContextTend; use the owning tool's workflow.",
  "",
  "## Promotion",
  "",
  "Move uncertain knowledge through observation -> candidate -> review -> durable",
  "knowledge. Put unresolved proposals in `.contexttend/candidates/` with claim,",
  "role, evidence, confidence, proposed owner, and recommended destination.",
  "A candidate must preserve the substance needed for later review. A Git ref",
  "or statement that old content existed is supporting evidence, not a claim.",
  "",
  "## Evidence",
  "",
  "Every semantic finding names the claim, canonical source, conflicting or",
  "supporting evidence, confidence, and recommended action. `unknown` is valid;",
  "fabricated certainty is not.",
);

const ONBOARD_SKILL = lines(
  "---",
  "name: context-onboard",
  "description: Onboard a repository on the first substantive Codex task after ContextTend init. Use automatically when `.contexttend/state.json` has no `lastOnboarding`, or explicitly via $context-onboard, to audit and route existing AGENTS.md and overlapping project knowledge before normal work.",
  "---",
  "",
  "# Context onboarding",
  "",
  "Complete the semantic half of ContextTend initialization, then return to the",
  "user's original task. Deterministic `contexttend init` owns structure; this",
  "Skill owns evidence-backed understanding, consolidation, and routing.",
  "Onboarding is lossless before it is concise: never make user-authored",
  "knowledge discoverable only through Git history.",
  "",
  "## Related Skills",
  "",
  "Read a related Skill's `SKILL.md` completely before using that phase. Its",
  "current contract wins; do not duplicate or weaken it here.",
  "",
  "- `$harness-audit full`: verify non-managed AGENTS content and existing Codex",
  "  Skills, plugins, configuration, or discovery assumptions. It reports only.",
  "- `$memory-audit`: report stale, contradictory, duplicate, unsupported,",
  "  misowned, and overloaded durable knowledge before consolidation.",
  "- `$context-bootstrap`: fill missing native sources from verified evidence",
  "  after existing sources and external owners have been identified.",
  "- `$context-sync`: maintain durable knowledge after onboarding and material",
  "  repository changes; it is not a substitute for first-run consolidation.",
  "",
  "## Workflow",
  "",
  "1. Preserve the user's original request. Locate the repository root; read",
  "   `.contexttend/state.json`, `.contexttend/registry.yaml`, and the governance",
  "   guide completely. If `lastOnboarding` is already set and onboarding was not",
  "   explicitly requested, resume the original task without rerunning this flow.",
  "2. Run `contexttend validate`. Stop semantic writes when deterministic",
  "   infrastructure is invalid and report the exact remediation. Confirm",
  "   `.contexttend/agents-coverage.json` represents the original source. For a",
  "   legacy or repair run, capture a trusted pre-migration file or Git ref first.",
  "3. When user-authored AGENTS content exists, read",
  "   [references/agents-migration.md](references/agents-migration.md) completely",
  "   and follow its lossless protocol. Read `AGENTS.md` completely, in chunks if",
  "   needed; never infer coverage from a summary or file-size comparison. In a",
  "   repair run, read the exact original path/ref named by the coverage baseline,",
  "   not only the already-condensed working-tree AGENTS file.",
  "4. Inventory conventional documentation, registered sources, external",
  "   framework artifacts, code, tests, and configuration. Read likely canonical",
  "   sources first and expand only where a claim overlaps, conflicts, or lacks",
  "   evidence. Never create a second source of truth owned by an adapter.",
  "5. When non-managed AGENTS content or a non-ContextTend Codex harness exists,",
  "   use `$harness-audit full` as a read-only phase. When sources overlap or",
  "   freshness is doubtful, use `$memory-audit` as a read-only phase. Continue",
  "   only with findings supported by repository or authoritative evidence.",
  "6. Build an atomic source-coverage ledger before mutation. Classify every",
  "   substantive source span and nested rule as `KEEP`, `MOVE`, `CONDENSE`,",
  "   `CANDIDATE`, `REMOVE`, or `EXTERNAL`, with source lines, claim, evidence,",
  "   confidence, destination, owner, and action. `REMOVE` requires evidence that",
  "   the item is obsolete or exactly duplicated; unsupported items are candidates.",
  "7. Present one `ONBOARDING PLAN` before mutation. Include files to change,",
  "   exact knowledge routing, conflicts and unknowns, content that would remain",
  "   in AGENTS.md, and content proposed for removal. Ask for confirmation before",
  "   shortening, replacing, or removing pre-existing user-authored content unless",
  "   the user's current request already explicitly authorizes that migration.",
  "8. Apply the approved plan in two stages. First write and verify every durable",
  "   destination and self-contained candidate while leaving original AGENTS text",
  "   intact. Then shorten AGENTS only after the ledger has no uncovered source",
  "   span. Use subsystem documents under a registered documentation directory",
  "   when exact configuration, retry, threshold, state, allowlist, or lifecycle",
  "   rules would overload a canonical overview. Never modify external/generated",
  "   sources directly.",
  "9. Recheck every ledger row against its actual destination. Run",
  "   `contexttend agents-coverage check`, `contexttend validate`, and",
  "   `contexttend diff`. Missing anchors block completion; missing old headings",
  "   require explanation. On success, run `contexttend record sync` and",
  "   `contexttend record onboarding`. The latter independently enforces anchor",
  "   coverage. Do not record when claims were dropped or review is incomplete.",
  "10. Report sources inspected, Skill phases used or skipped, files changed,",
  "    claims kept/moved/condensed/candidate/removed, unknowns, and validation.",
  "    Then resume the user's original task unless it is no longer applicable.",
  "",
  "A completed onboarding may retain explicit unknowns and self-contained",
  "candidates. A candidate containing only a Git ref or a pointer to deleted text",
  "does not preserve knowledge and blocks source removal. Do not",
  "rerun it merely because code changed; use sync or the focused audits instead.",
  "Never edit ContextTend-managed assets or machine state directly.",
);

const ONBOARD_AGENTS_MIGRATION_REFERENCE = lines(
  "# Lossless AGENTS.md migration",
  "",
  "Use this protocol whenever onboarding may shorten or reorganize pre-existing",
  "user-authored AGENTS content. The objective is not to preserve every sentence",
  "verbatim; it is to preserve every still-relevant rule, constraint, rationale,",
  "exception, workflow, and unresolved claim in an immediately discoverable source.",
  "",
  "## Conservation invariant",
  "",
  "Before source removal, every substantive non-managed source span must have one",
  "explicit disposition and a real destination. Git history is recovery evidence,",
  "not an active knowledge destination. Preserve exact operational details such as",
  "configuration names, thresholds, timing, retry/cooldown behavior, allowlists,",
  "state compatibility, failure isolation, security constraints, and exceptions.",
  "Do not collapse several independently actionable nested bullets into one vague",
  "summary.",
  "",
  "## Establish the source baseline",
  "",
  "Fresh `contexttend init --apply` captures `.contexttend/agents-coverage.json`",
  "before adding the managed block. For a legacy installation or repair, preview",
  "and then capture a trusted source before mutation:",
  "",
  "```text",
  "contexttend agents-coverage snapshot . --source AGENTS.md --git-ref <ref>",
  "contexttend agents-coverage snapshot . --source AGENTS.md --git-ref <ref> --apply",
  "```",
  "",
  "When the original was not committed, keep an untracked copy at",
  "`.contexttend/original-agents-source.md` and use that with `--source` instead",
  "of `--git-ref`. This location is outside the active coverage corpus. Never",
  "capture the already-condensed file as though it were the original. During",
  "repair, also read that exact source file or `git show <ref>:AGENTS.md` completely;",
  "the baseline contains lexical anchors, not the full semantic source.",
  "",
  "## Build the source-coverage ledger",
  "",
  "Read the entire source in bounded chunks. Create a ledger before editing:",
  "",
  "| ID | Source lines | Knowledge item | Kind | Evidence | Disposition | Destination | Owner |",
  "| --- | --- | --- | --- | --- | --- | --- | --- |",
  "",
  "Line ranges must cover every substantive source line without unexplained gaps.",
  "Split a section when its nested rules have different evidence or destinations.",
  "Use these routing defaults:",
  "",
  "- always-on agent behavior and navigation -> concise `AGENTS.md`;",
  "- human product intent, goals, and non-goals -> registered human-owned sources;",
  "- architecture and accepted decisions -> registered architecture/decision sources;",
  "- detailed subsystem behavior and configuration -> `docs/context/<subsystem>.md`",
  "  or another registered canonical implementation-context directory;",
  "- employee/user procedures -> their existing owner and instruction files;",
  "- adapter-owned specs/plans -> the external source without rewriting it;",
  "- unverified, conflicting, or possibly stale content -> a self-contained candidate.",
  "",
  "A candidate must restate the claim, source location, evidence, uncertainty, owner,",
  "and intended destination. Redact secret values while preserving variable names and",
  "security meaning. A file that says only `see <commit>:AGENTS.md` is incomplete.",
  "",
  "## Apply in two stages",
  "",
  "1. Write destinations and candidates while the original AGENTS text remains.",
  "2. Verify each ledger row against the written destination and resolve overlap.",
  "3. Only then replace detail in AGENTS with concise rules and direct navigation.",
  "4. If the run cannot finish, leave AGENTS unshortened and leave onboarding unset.",
  "",
  "## Coverage gate",
  "",
  "Run the deterministic check after writing destinations and again after shortening:",
  "",
  "```text",
  "contexttend agents-coverage check .",
  "```",
  "",
  "The default corpus includes registered non-evidence knowledge, common repository",
  "documentation, employee instructions, and self-contained candidates; it excludes",
  "implementation code and tests so an identifier cannot pass merely because it still",
  "exists in code. Use repeated `--target` values only when an approved durable source",
  "is outside those defaults. Zero missing anchors is required. Old heading coverage is",
  "diagnostic: explain every missing heading through the ledger.",
  "",
  "The check is intentionally conservative and lexical. It catches vanished config",
  "names, paths, flags, and symbols, but cannot prove semantic truth or completeness.",
  "The ledger review remains the semantic gate.",
  "",
  "## Completion report",
  "",
  "Report source line/section/anchor counts and totals for KEEP, MOVE, CONDENSE,",
  "CANDIDATE, REMOVE, and EXTERNAL. The disposition totals must equal the ledger",
  "item count. Name every destination, every intentionally obsolete item, unresolved",
  "candidate, missing heading explanation, and the final coverage-check result.",
);

const BOOTSTRAP_SKILL = lines(
  "---",
  "name: context-bootstrap",
  "description: Bootstrap or repair missing or placeholder typed project knowledge after ContextTend init. Use when canonical knowledge is incomplete or the user invokes $context-bootstrap; do not replace an external spec framework.",
  "---",
  "",
  "# Context bootstrap",
  "",
  "Create useful durable knowledge from repository evidence without inventing",
  "product intent.",
  "",
  "## Workflow",
  "",
  "1. Locate the repository root and read `.contexttend/registry.yaml` completely.",
  "2. Read `.contexttend/guides/agent-governance.md` completely.",
  "3. Run `contexttend validate`. Stop semantic writes if deterministic",
  "   infrastructure is invalid; report the exact findings.",
  "4. Build a role coverage table from the registry. Treat external adapter",
  "   sources as read-only and use them instead of parallel ContextTend docs.",
  "5. Route progressively: read canonical goals/product first when needed, then",
  "   only architecture, requirements, decisions, plans, code, and tests relevant",
  "   to each missing claim. Do not read every spec or decision by default.",
  "6. Fill missing or placeholder knowledge in native sources only, including",
  "   scaffold `Unknown` sections. Preserve complete verified content. For `human`",
  "   ownership, use direct user statements or clearly cited existing product",
  "   documentation. If intent is unavailable, write",
  "   `Unknown - human confirmation required` and list the evidence inspected;",
  "   never turn code behavior into a product requirement.",
  "7. For `shared` sources, state the verified evidence behind every durable",
  "   claim. For `agent` sources, keep summaries concise and reproducible.",
  "8. Put disputed observations in `.contexttend/candidates/`; do not promote",
  "   them merely because they appear implemented.",
  "9. Run `contexttend validate` again and report sources read, files changed,",
  "   unknowns, candidates, and validation outcome.",
  "",
  "Never modify `.contexttend/state.json`, managed Skill files, generated files,",
  "or external framework artifacts directly.",
);

const SYNC_SKILL = lines(
  "---",
  "name: context-sync",
  "description: Perform a documentation impact check after material repository changes. Use when the user invokes $context-sync or asks whether durable project knowledge must change.",
  "---",
  "",
  "# Context sync",
  "",
  "Determine whether repository changes require durable knowledge updates.",
  "",
  "## Workflow",
  "",
  "1. Read `.contexttend/registry.yaml` and the governance guide completely.",
  "2. Run `contexttend validate` and `contexttend diff`.",
  "3. Inspect `git status --short`, the relevant git diff, changed tests, and",
  "   active external specs/plans. Never store raw transcripts.",
  "4. Answer each impact question with yes/no/unknown and evidence:",
  "   product behavior, architecture, business rule, public interface, security",
  "   assumption, reliability behavior, durable decision, accepted limitation,",
  "   and completed plan.",
  "5. Route only to registered roles affected by a yes/unknown answer.",
  "6. Apply ownership policy. Human-owned meaning needs direct user evidence;",
  "   shared knowledge needs a confirmed project change; agent-owned summaries",
  "   may be maintained from strong evidence; external/generated sources are not",
  "   edited through ContextTend.",
  "7. Write uncertain claims as candidates. If every answer is no, explicitly",
  "   report `No durable knowledge update required.`",
  "8. Run validation again. If successful, run `contexttend record sync`.",
  "",
  "Report the evidence, affected role, canonical destination, ownership decision,",
  "and exact changes. Do not update documentation simply because files changed.",
);

const MEMORY_AUDIT_SKILL = lines(
  "---",
  "name: memory-audit",
  "description: Audit durable project knowledge against repository evidence for staleness, contradiction, duplication, orphaning, unsupported claims, supersession, missing sources, ownership errors, and overload. Read-only except for the audit report.",
  "---",
  "",
  "# Memory audit",
  "",
  "Audit whether durable knowledge still matches the project.",
  "",
  "## Workflow",
  "",
  "1. Read the registry and governance guide. Run `contexttend validate` and",
  "   include its findings rather than rediscovering path/schema facts.",
  "2. Inventory registered sources by role, authority, owner, and adapter.",
  "3. Use progressive disclosure. For each claim under review, inspect its",
  "   canonical source and only the relevant code, tests, plans, decisions, or",
  "   external artifacts.",
  "4. Check every class: `STALE`, `CONTRADICTORY`, `DUPLICATE`, `ORPHAN`,",
  "   `UNSUPPORTED`, `SUPERSEDED`, `MISSING`, `MISOWNED`, and `OVERLOADED`.",
  "5. Explicitly test for stale architecture, contradictory product rules,",
  "   duplicate canonical sources, completed active plans, and missing registered",
  "   files. Absence of evidence is not automatically a contradiction.",
  "6. Assign P0 dangerous contradiction, P1 material stale knowledge, P2",
  "   structural problem, or P3 optional cleanup.",
  "7. Every finding must include: Finding, Claim, Canonical source, Conflicting",
  "   evidence, Confidence, and Recommended action. Omit unsupported guesses.",
  "8. Write `.contexttend/audits/YYYY-MM-DD-memory.md`. Do not change project",
  "   knowledge during the audit. Then run `contexttend record memory-audit`.",
  "",
  "The report begins with scope, registry version, commit or working-tree state,",
  "and deterministic validation summary. A clean audit is a valid result.",
);

const HARNESS_AUDIT_SKILL = lines(
  "---",
  "name: harness-audit",
  "description: Research current official Codex guidance and audit this repository's AGENTS.md, Skills, plugins, configuration, discovery paths, and adapter assumptions. Use $harness-audit for incremental checks or $harness-audit full for reconsideration.",
  "---",
  "",
  "# Harness audit",
  "",
  "Audit the coding-agent configuration, not the product.",
  "",
  "## Source policy",
  "",
  "Use fresh network research. Official OpenAI Codex/developer documentation and",
  "release notes are AUTHORITATIVE; explicit official recommendations are",
  "OFFICIAL_RECOMMENDATION; Cookbook examples are OFFICIAL_EXAMPLE; OpenAI",
  "engineering reports are EXPERIMENTAL_PRACTICE; community sources are",
  "COMMUNITY_PRACTICE and never override official sources.",
  "",
  "## Workflow",
  "",
  "1. Read `.contexttend/source-registry.yaml`, the registry, and governance guide.",
  "2. Without `full`, research changes since each relevant `lastChecked`; with",
  "   `full`, reconsider every recorded assumption.",
  "3. Fetch primary pages, not search snippets. Check AGENTS discovery and size",
  "   behavior, `.agents/skills` discovery, Skill metadata, plugin packaging,",
  "   Codex configuration, changelog/release notes, relevant Cookbook material,",
  "   OpenAI engineering publications, and external adapter contracts.",
  "4. Compare sources with the repository. Look for obsolete/conflicting rules,",
  "   changed discovery paths, overly large always-on context, deprecated config,",
  "   locally modified managed assets, and stale adapter assumptions.",
  "5. For every finding cite URL, source class, checked date, repository evidence,",
  "   confidence, and a reviewable proposal.",
  "6. Write `.contexttend/audits/YYYY-MM-DD-harness.md`. Do not migrate or rewrite",
  "   the project during the audit.",
  "7. After a successful report run",
  "   `contexttend record harness-audit --source openai-codex-docs`.",
  "",
  "Migration is always a separate explicit CLI operation. Never silently reshape",
  "AGENTS.md, Skills, framework directories, or semantic project knowledge.",
);

export const SYSTEM_ASSET_CONTENTS: Readonly<Record<string, string>> = {
  ".contexttend/guides/agent-governance.md": GOVERNANCE_GUIDE,
  ".contexttend/audits/.gitkeep": "",
  ".contexttend/candidates/.gitkeep": "",
  ".agents/skills/context-onboard/SKILL.md": ONBOARD_SKILL,
  ".agents/skills/context-onboard/references/agents-migration.md":
    ONBOARD_AGENTS_MIGRATION_REFERENCE,
  ".agents/skills/context-bootstrap/SKILL.md": BOOTSTRAP_SKILL,
  ".agents/skills/context-sync/SKILL.md": SYNC_SKILL,
  ".agents/skills/memory-audit/SKILL.md": MEMORY_AUDIT_SKILL,
  ".agents/skills/harness-audit/SKILL.md": HARNESS_AUDIT_SKILL,
};

export const SYSTEM_ASSET_HASHES: Readonly<Record<string, string>> =
  Object.fromEntries(
    Object.entries(SYSTEM_ASSET_CONTENTS).map(([assetPath, content]) => [
      assetPath,
      sha256(content),
    ]),
  );

export const DEFAULT_CONFIG: Config = {
  version: 1,
  mode: "adaptive",
  agentIntegration: true,
  createMissingNativeSources: true,
};

export function defaultExternalSourceRegistry(
  checkedDate: string,
): ExternalSourceRegistry {
  return {
    version: 1,
    sources: {
      "openai-codex-docs": {
        authority: "authoritative",
        url: "https://learn.chatgpt.com/docs",
        lastChecked: checkedDate,
        relevantTopics: [
          "agents-md",
          "skills",
          "plugins",
          "configuration",
          "changelog",
        ],
      },
      "openai-codex-engineering": {
        authority: "experimental-practice",
        url: "https://openai.com/index/harness-engineering/",
        lastChecked: checkedDate,
        relevantTopics: [
          "progressive-disclosure",
          "repository-knowledge",
          "mechanical-validation",
        ],
      },
      "github-spec-kit": {
        authority: "authoritative",
        url: "https://github.com/github/spec-kit",
        lastChecked: checkedDate,
        relevantTopics: ["adapter", "specs", "skills-mode"],
      },
    },
  };
}

export const NATIVE_SOURCE_TEMPLATES: Readonly<Record<string, string>> = {
  "docs/GOALS.md": lines(
    "# Project goals",
    "",
    "Authority: human-owned canonical product intent.",
    "",
    "## Goals",
    "",
    "Unknown - human confirmation or `$context-bootstrap` with direct product",
    "evidence is required.",
    "",
    "## Non-goals",
    "",
    "Unknown - do not infer non-goals from missing implementation.",
    "",
    "## Success signals",
    "",
    "Unknown - define measurable outcomes with the project owner.",
  ),
  "docs/PRODUCT.md": lines(
    "# Product",
    "",
    "Authority: human-owned canonical product knowledge.",
    "",
    "## Problem and users",
    "",
    "Unknown - human confirmation or existing authoritative product evidence is",
    "required.",
    "",
    "## Product behavior",
    "",
    "Unknown - implementation behavior is evidence, not product intent.",
    "",
    "## Constraints",
    "",
    "No product constraints have been verified yet.",
  ),
  "docs/PLANS.md": lines(
    "# Plans",
    "",
    "Authority: shared canonical roadmap.",
    "",
    "## Active",
    "",
    "No active durable plan has been verified.",
    "",
    "## Completed",
    "",
    "No completed plan has been recorded.",
    "",
    "Move completed work out of Active only after verification evidence exists.",
  ),
  "docs/decisions/README.md": lines(
    "# Decisions",
    "",
    "Record durable architectural decisions here when no external decision system",
    "already owns them. Each decision should include context, decision,",
    "consequences, status, and evidence. Do not duplicate Spec Kit, OpenSpec,",
    "Agent OS, or GSD decisions.",
  ),
  "docs/context/README.md": lines(
    "# Implementation context",
    "",
    "Agent-maintained, evidence-backed summaries may live here. Keep them small,",
    "typed, and reproducible from code or tests. Do not store session transcripts",
    "or restate human product intent.",
  ),
};

export const CONTEXTTEND_META = lines(
  "<!-- contexttend:generated -->",
  "# ContextTend installation",
  "",
  `Managed by ContextTend ${CONTEXTTEND_VERSION}.`,
  "",
  "Use `.contexttend/registry.yaml` for the knowledge map and",
  "`.contexttend/state.json` for machine state. Do not edit managed assets by hand.",
);
